version: "3.8"


services:
    web:
        build: 
            context: ./web
            args:
                - USE_PROXY=1 # (Set to null (empty) if not using proxy during build!)
        env_file:
            - .env
        ports:
            - "3000:3000"
        restart: unless-stopped
        environment:
            API_BASE_URL: http://localhost:5000
            WEB_BASE_URL: http://localhost:3000

        # volumes:
        #   - ./web/src:/code/src
        #   - ./data?:/data?


    # api:
    #     build: ./app
    #     platform: linux/amd64
    #     restart: unless-stopped
    #     ports:
    #         - "5000:5000"
    #     volumes:
    #         - ./app:/code
    #         - ./dataForWeb:/dataForWeb
    #         - ./web/build:/web/build
    #     env_file:
    #         - .env
    #     environment:
    #         ENCRYPTION_KEY: ${ENCRYPTION_KEY}
    #         AUTH_ENABLED: ${AUTH_ENABLED}
    #         OAUTH_AUDIENCE: ${OAUTH_AUDIENCE}
    #         OAUTH_JWK_URL: ${OAUTH_JWK_URL}
    #         FLASK_DEBUG: 1
    #         FLASK_ENV: development
    #         FLASK_HOST: 0.0.0.0
    #         FLASK_APP_PORT: 5000
    #         MONGODB_DATABASE: sessionDatabase
    #         MONGODB_USERNAME: user1
    #         MONGODB_PASSWORD: 123
    #         MONGODB_HOSTNAME: mongodb
    #         ENVIRONMENT: local #remember to update this in prod!
    #     depends_on:
    #         - mongodb

    # mongodb:
    #     image: mongo:4.2.16
    #     volumes:
    #         - ./database:/data/db
    #         - ./mongo:/mongo
    #     container_name: mongodb
    #     restart: unless-stopped
    #     command: --auth

    # db-ui:
    #     image: mongo-express:0.54
    #     restart: unless-stopped
    #     ports:
    #         - "8082:8081"
    #     environment:
    #         ME_CONFIG_MONGODB_SERVER: mongodb
    #         ME_CONFIG_MONGODB_ADMINUSERNAME: admin
    #         ME_CONFIG_MONGODB_ADMINPASSWORD: pw
    #         ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"

