version: "3.8"


services
    web:
        build: 
            context: ./web
            args:
                - USE_PROXY=1 # (Set to null (empty) if not using proxy during build!)
        env_file:
            - .env
        ports:
            - "3000:3000"
        restart: unless-stopped
        environment:
            API_BASE_URL: http://localhost:5000
            WEB_BASE_URL: http://localhost:3000

        # volumes:
        #     - ./web/src:/code/src


